name: CI/CD Pipeline
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read
  actions: read
  
jobs:
  set-env:
    name: ' '
    uses: maalcantara/reusable_workflow/.github/workflows/rwf_set_environment.yml@main

  build_app:
    name: ' '
    needs: set-env
    uses: maalcantara/reusable_workflow/.github/workflows/rwf_build_java.yaml@main
    with:
      maven_cli_opts_input: "-s .m2/settings.xml --batch-mode --update-snapshots"
      artifact_path_input: target/crm-admin-service.jar
      java_version_input: 13
      # java_distribution_input:
    secrets: inherit

  sonar:
    name: ' '
    uses: maalcantara/reusable_workflow/.github/workflows/rwf_sonar_maven.yaml@main
    with:
      maven_cli_opts_input: "-s .m2/settings.xml --batch-mode --update-snapshots"
      java_version_input: 13
      # sonar_version_input: 3.11.0.3922
      # java_distribution_input:
    secrets: inherit

  build_image:
    name: ' '
    needs: [set-env,build_app]
    uses: maalcantara/reusable_workflow/.github/workflows/rwf_docker-build-push.yaml@main
    with:
      environment_input: ${{ needs.set-env.outputs.set_env }}
      dockerfilePath_input: Dockerfile
      buildcontext_input: .
      push_image_input: true
      artifact_path_input: target/crm-admin-service.jar
    secrets: inherit

  deploy:
    name: ' '
    needs: [set-env,build_app,build_image]
    permissions:
      id-token: write
      contents: read
      actions: read
    uses: maalcantara/reusable_workflow/.github/workflows/rwf_aks.yaml@main
    with:
      environment_input: ${{ needs.set-env.outputs.set_env }}
      secret_input: true
    secrets: inherit