name: Setup .NET Core SDK

on:
  workflow_call:
    inputs:
      dotnet_version:
        required: true
        type: string

jobs:
  setup-dotnet:
    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet_version }}